#ifndef RUNTIME_CONSTANTS_H
#define RUNTIME_CONSTANTS_H

#define POINTER_SIZE 4

#define FUNCTION_CONTEXT_HEADER_SIZE 5 * POINTER_SIZE

#define FUNCTION_CONTEXT_PARAMS_OFFSET 5

#define SPILL_AREA_FROM_EBP_OFFSET 3

#define TAG_SHIFT 1

#define INT_TAG 0
#define PTR_TAG 1
#define INT_PTR_TAG_MASK 1

#endif
