all: runtime.cpp builtins.cpp memory.h memory.cpp stack_walk.cpp stack_walk.h constants.h
	g++ -m32 -std=c++11 -c runtime.cpp -o runtime.o
	g++ -m32 -std=c++11 -c builtins.cpp -o builtins.o
	g++ -m32 -std=c++11 -c memory.cpp -o memory.o
	g++ -m32 -std=c++11 -c stack_walk.cpp -o stack_walk.o
