POINTER_SIZE = 4
INT_TAG_MULTIPLIER = 2
INT_TAG_SHIFT = 1
PTR_TAG = 1
INT_TAG = 0
INT_PTR_TAG_MASK = 1

FUNCTION_CONTEXT_HEADER_SIZE = 5 * POINTER_SIZE

# FunctionContext offsets
FUNCTION_CONTEXT_OFFSET_OUTER_FUNCTION_CONTEXT = 0
FUNCTION_CONTEXT_OFFSET_SPILL_COUNT = 2
FUNCTION_CONTEXT_OFFSET_STRING_TABLE = 4
FUNCTION_CONTEXT_OFFSET_PARAMS = 5

# Function offsets
FUNCTION_OFFSET_FUNCTION_CONTEXT = 0
FUNCTION_OFFSET_ADDRESS = 1
FUNCTION_OFFSET_RETURN_VALUE = 2

# These need to be multiplied by POINTER_SIZE.
SPILL_AREA_FROM_EBP_OFFSET = -3
FUNCTION_CONTEXT_FROM_EBP_OFFSET = -2

MAIN_NAME = "__main"

# Errors
ERROR_ID_ASSERT_FAILURE = 0
ERROR_ID_ARITHMETIC_OPERATION_PARAMETER_NOT_INT = 1
ERROR_ID_ARRAY_INDEX_NOT_INT = 2
ERROR_ID_ARRAY_BASE_NOT_ARRAY = 3

# Optimization flags
OPTIMIZE_VARIABLES_IN_TEMPORARIES = True
